[package]
name = "cmd-srv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "time"] }
paho-mqtt = "0.9.1"
futures = "0.3"